### ISSUE TITLE
How to modify the request params? / No API response 

### ISSUE THREAD

**Issue by 0x80** [nxtedition/node-http2-proxy#20]
I'm trying to forward a request and inject an API key into the request, so that the client doesn't have to know / expose the key.  

I was looking at the example where the request is modified in onReq, however I am running into a few issues.

When calling the proxy code below on node (v8.7) it crashes with the message:

> _stream_readable.js:583
  dest.on('unpipe', onunpipe);
       ^
> TypeError: dest.on is not a function
    at IncomingMessage.Readable.pipe (_stream_readable.js:583:8)
    at proxy (/Users/me/myproject/node_modules/http2-proxy/index.js:136:6)

Also, according to Typescript  `res.headers` is not available...

```typescript
import * as http from "http";
import * as proxy from "http2-proxy";

const server = http.createServer();
server.listen(8008);

server.on("request", async (req, res) => {
  req.params.appId = "234253";
  req.params.appKey = "asdfsadlkajfglkdjgslkfdjgfd";

  try {
    await proxy.web(req, res, {
      hostname: "https://api.flightstats.com",
      onReq: (req, res) => {
        // @ts-ignore
        res.headers["x-forwarded-host"] = req.headers.host!;
        return true;
      }
    });
  } catch (err) {
    console.error("Failed to proxy:", err.stack);
  }
});
```
 
Also I would like to do this in an existing express app. Is there anything keeping me from combining http2-proxy with express? Are there any examples available maybe?

**Comment by 0x80** [comment]
I have managed to get further with enabling ssl. Maybe that's a requirement? Also I have connected my proxy handler to a route in express.

The server code: 
```typescript
import * as express from "express";
import * as https from "https";
import * as fs from "fs";
import { join } from "path";
import flightstats from "./proxy/flightstats";

const app = express();
app.enable("trust proxy");
app.get("/", (req, res) => {
  res.send("Safe and secure!");
});

app.use("/api/flightstats", flightstats);

const key = fs.readFileSync(join(__dirname, "..", "ssl", "key.pem"));
const cert = fs.readFileSync(join(__dirname, "..", "ssl", "cert.pem"));

const server = https.createServer(
  {
    key,
    cert,
    passphrase: "something"
  },
  app
);

server.listen(8008);
console.log("Listening on 8008");

```
The `./proxy/flightstats` code:

```typscript
import { Router } from "express";
import * as proxy from "http2-proxy";

const router = Router();

router.get("/*", async (req, res) => {
  console.log(`Proxy clientRequest url: ${req.url}`);

  try {
    await proxy.web(req, res, {
      hostname: "api.flightstats.com",
      port: 443
    });
  } catch (err) {
    console.error(`Proxy failed: ${err.message}`);
  }
});

export default router;
```

Then I make a call with 
`$ curl --cacert ./ssl/cert.pem https://localhost:8008/api/flightstats/flex/airports/rest/v1/json/all`

And I get the following output:

>Proxy clientRequest url: /flex/airports/rest/v1/json/all
Proxy failed: socket hang up

Any idea what might be going wrong here?

**Comment by ronag** [comment]
`onReq` should return undefined or a `HttpRequest` also the second argument is not the res object.

I think what you want to do is:

```js
    await proxy.web(req, res, {
      hostname: "https://api.flightstats.com",
    onReq: (req, { headers }) => {
      headers['x-forwarded-host'] = req.headers['host']
    }
    });
```

**Comment by ronag** [comment]
> And server console output:
> 
> Proxy clientRequest url: /flex/airports/rest/v1/json/all
> Proxy failed: socket hang up
> Any idea what might be going wrong here?

Could you try and verify a request directly against upstream? Could you give me a reproducible example so I can try it myself?

**Comment by 0x80** [comment]
@ronag here you go https://github.com/0x80/http2-proxy-example

Thanks for looking into it.

**Comment by 0x80** [comment]
BTW meanwhile I've come to the conclusion that the req.params in express are just parsed from the url, so I shouldn't try to modify them. I think the right approach would be to rewrite the request path/url in order to append them. But I haven't managed to find out how to do that yet.

**Comment by ronag** [comment]
Sorry for no response. Glad you figured it out.
