### ISSUE TITLE
Proxy from https to https

### ISSUE THREAD

**Issue by Muhaah** [nxtedition/node-http2-proxy#21]
Proxying to a https target are not working. Some option for this case would-be cool and an option to allow self-signed certificate from target (rejectUnauthorized: false).

**Comment by ronag** [comment]
You can achieve this using `onReq`, e.g:

```js

server.on('request', (req, res) => {
  proxy.web(req, res, {
    hostname: 'localhost'
    port: 9000,
    onReq: (options) => https.request({
      ...options,
      rejectUnauthorized: false
    })
  }, err => {
    if (err) {
      console.error('proxy error', err)
    }
  })
})
```

**Comment by Muhaah** [comment]
Works great 👍 
And the request/response will be handled from node-http2-proxy?

**Comment by ronag** [comment]
Correct.
