### ISSUE TITLE
websockets don't proxy with 5.0.34 if the path isn't the same unless onReq is used

### ISSUE THREAD

**Issue by risacher** [nxtedition/node-http2-proxy#32]
I have a reverse-proxy server that works fine with 4.2.15, and proxies both web and ws traffic.  WIth 5.0.34 it does not proxy ws connections correctly if the path is mapped to a different route.
```
// works 4.2.15, not 5.0.34:
const upgrade = function (req, socket, head) {
    var target = route(req);
    if (null != target) {
        proxy.ws(req, socket, head, target, defaultWSHandler);
  } else {
    socket.close()
  }
};
```
The above code doesn't work for websockets with 5.0.34 if the proxy target has a different path than the request.  (i.e. ws://fqdn/app/socketEndpoint is proxied to ws://localhost:4000/socketEndpoint) Instead, I get errors on both server and client: "ws proxy error Error: socket hang up" and 'WebSocket connection to 'wss://servername.org:3003/alt/socketEndpoint' failed: Connection closed before receiving a handshake response"

The following code, that uses an onReq handler to create the proxy request does not have this issue:
```
// works in 5.0.34 (and 4.2.15)
const upgrade2 = function (req, socket, head) {
    var target = route(req);
    if (null != target) {
        proxy.ws(req, socket, head, {
            onReq: (req, options) => {
                options.host = target.host;
                options.hostname = target.hostname;
                options.port = target.port;
                options.path = target.path;
                var r = (target.protocol.match(/^(http|ws):?$/))?
                    http.request(options)
                    : https.request(options);
                return r;
            }
        }, defaultWSHandler);
  } else {
    socket.close()
  }
};
```
This issue has become low-priority since I found this workaround, but it still seems like there's a bug in there somewhere.  My original proxy used onReq for web traffic to add X-proxy-for headers, but didn't use an onReq handler for ws traffic, (since the websocket apps don't usually pay attention to the proxy headers anyway.)

**Comment by risacher** [comment]
https://github.com/risacher/http2-proxy-bug-demo

**Comment by ronag** [comment]
Thank you for reporting this. Should be resolve in 5.0.35.
