### ISSUE TITLE
Forwarding to unix socket

### ISSUE THREAD

**Issue by skerit** [nxtedition/node-http2-proxy#35]
In `http-proxy` you can forward requests to a unix socket, using: `proxy.web(req, res, {target: {socketPath: '/some/path'}})`

I can't seem to find a way to do the same with this proxy though, but I need it to improve throughput.

**Comment by ronag** [comment]
@skerit: If you could provide a complete example I can take a look.

**Comment by ronag** [comment]
I believe something like this should work:

```js
server.on('request', (req, res) => {
  proxy.web(req, res, {
    socketPath: '/tmp/static0.sock',
    path: '/volumes/list',
  }, defaultWebHandler)
})
```

**Comment by ronag** [comment]
With 5.0.45

**Comment by skerit** [comment]
That was very quick, thanks! I'm gonna try it now
