### ISSUE TITLE
Possible wrong type for onReq

### ISSUE THREAD

**Issue by ajbouh** [nxtedition/node-http2-proxy#52]
https://github.com/nxtedition/node-http2-proxy/blob/db655116389a284bd5a3377688a146bfe3bdd369/index.d.ts#L107

Based on my experiments, I never seem to get a `ServerResponse` for `proxyRes`. Both the node documentation and inspecting runtime values suggest that `proxyRes` should actually be an `IncomingMessage`

**Comment by ronag** [comment]
> should actually be an IncomingMessage

You are right. PR welcome!

**Comment by jsmylnycky** [comment]
Ran into this today while checking out this repo :)

https://github.com/nxtedition/node-http2-proxy/pull/64/files should correct it

**Comment by jsmylnycky** [comment]
@ronag Good morning! When you get a moment, would you mind cutting a new patch release to include the updated types please?

Thanks so much for the quick merge.
