### ISSUE TITLE
Issue with custom response streams handler

### ISSUE THREAD

**Issue by vladmandic** [nxtedition/node-http2-proxy#53]
I'm using **http2-proxy** with a custom `onRes` handler to do passthrough compression on the response stream.
And the results are really weird - it works perfectly with Chrome as client, but with Firefox the data received by client seems truncated by one byte (which of course results in error on the client)!

E.g., if the target server sends a JSON, it will be fine received by Firefox except closing '}' is missing!
Same on binary files.

And I've tried with gzip and brotli.

```js
const zlib = require('zlib');

app.use((req, res) => proxy.web(req, res, findTarget(req), errorHandler));

function findTarget(req) {
  // ...
  const res = {
    // ...
    onRes: (_req, output, input) => {
      const accept = _req.headers['accept-encoding'] ? _req.headers['accept-encoding'].includes('br') : false;
      if (accept) {
        // trid with zlib.createGzip() and content-encoding 'gzip' as well
        const compress = zlib.createBrotliCompress();
        output.setHeader('content-encoding', 'br');
        input.pipe(compress).pipe(output);
      } else {
        input.pipe(output);
      }   
    },
  };
  return res;
}
```

**Comment by ronag** [comment]
What version of node?

Can you provide a fully runnable example?

**Comment by vladmandic** [comment]
I think i figured it out, it's not **http2-proxy** fault.

If the target server sets `content-length` in a http header, it won't match size after compression.
Which doesn't bother Chrome the least, but makes Firefox go crazy on some responses.

If I strip `content-length` from response headers inside http2-proxy `onRes` handler, everything works just fine.

```js
  for (const [key, val] of Object.entries(input.headers)) {
    if (compress && key.toLowerCase().includes('content-length')) output.setHeader('content-length-original', val);
    else output.setHeader(key, val);
  }
  if (compress) output.setHeader('content-encoding', 'br');
```
